package v4l2

/*
#include <linux/v4l2-controls.h>
*/
import "C"

const (
	/* User-class control IDs */
	V4L2_CID_BRIGHTNESS           = C.V4L2_CID_BRIGHTNESS
	V4L2_CID_HUE                  = C.V4L2_CID_HUE
	V4L2_CID_EXPOSURE             = C.V4L2_CID_EXPOSURE
	V4L2_CID_AUTOBRIGHTNESS       = C.V4L2_CID_AUTOBRIGHTNESS
	V4L2_CID_POWER_LINE_FREQUENCY = C.V4L2_CID_POWER_LINE_FREQUENCY
)

/* Control classes */
const (
	V4L2_CTRL_CLASS_USER   = C.V4L2_CTRL_CLASS_USER
	V4L2_CTRL_CLASS_MPEG   = C.V4L2_CTRL_CLASS_MPEG
	V4L2_CTRL_CLASS_CAMERA = C.V4L2_CTRL_CLASS_CAMERA
	V4L2_CTRL_CLASS_JPEG   = C.V4L2_CTRL_CLASS_JPEG
)
